name: pull-request
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - uses: php-actions/composer@v6
        with:
          php_version: "8.0"
          args: --profile --ignore-platform-reqs
      - run: make analyze
      - run: make style